# Generated by Django 6.0.3 on 2026-03-22 05:08

import django.db.models.deletion
import hr_vault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(help_text="Employee's full name", max_length=200)),
                ('department', models.CharField(help_text="Employee's department", max_length=100)),
                ('bank_account_number', hr_vault.models.EncryptedField(editable=True, help_text='Bank account number (encrypted)')),
                ('annual_salary', hr_vault.models.EncryptedField(editable=True, help_text='Annual salary (encrypted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.CASCADE, related_name='added_employee_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Record',
                'verbose_name_plural': 'Employee Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
